alter table public.financial_entries add constraint financial_amount_positive check (amount > 0);
alter table public.products add constraint products_cost_nonnegative check (cost >= 0);
alter table public.products add constraint products_price_nonnegative check (price >= 0);
alter table public.products add constraint products_warranty_months_range check (warranty_months between 0 and 120);
alter table public.services add constraint services_price_nonnegative check (price >= 0);
alter table public.services add constraint services_cost_nonnegative check (cost >= 0);
alter table public.services add constraint services_warranty_days_range check (warranty_days between 0 and 3650);
alter table public.services add constraint services_followup_days_range check (followup_days between 0 and 3650);
alter table public.quote_items add constraint quote_items_quantity_positive check (quantity > 0);
alter table public.quote_items add constraint quote_items_unit_price_nonnegative check (unit_price >= 0);
alter table public.quote_items add constraint quote_items_unit_cost_nonnegative check (unit_cost >= 0);
alter table public.quote_items add constraint quote_items_position_nonnegative check (position >= 0);
alter table public.quotes add constraint quotes_discount_nonnegative check (discount >= 0);
alter table public.quotes add constraint quotes_surcharge_nonnegative check (surcharge >= 0);
alter table public.work_order_items add constraint wo_items_quantity_positive check (quantity > 0);
alter table public.work_order_items add constraint wo_items_unit_price_nonnegative check (unit_price >= 0);
alter table public.work_order_items add constraint wo_items_unit_cost_nonnegative check (unit_cost >= 0);
alter table public.work_order_materials add constraint wo_materials_quantity_positive check (quantity > 0);
alter table public.work_order_materials add constraint wo_materials_unit_cost_nonnegative check (unit_cost >= 0);
alter table public.purchase_items add constraint purchase_items_quantity_positive check (quantity > 0);
alter table public.purchase_items add constraint purchase_items_unit_cost_nonnegative check (unit_cost >= 0);
alter table public.subscriptions add constraint subscriptions_amount_nonnegative check (amount >= 0);
