from pathlib import Path
import json
ROOT=Path('.')

def fail(msg): raise SystemExit(msg)
def replace_once(text,old,new,label):
    c=text.count(old)
    if c!=1: fail(f"{label}: expected exactly 1 anchor, found {c}")
    return text.replace(old,new,1)

def wave7():
    p=ROOT/'api/quote-pdf.js'; s=p.read_text()
    s=replace_once(s,"import { supabaseServidor } from './_supabaseServerConfig.js';\n","import { supabaseServidor } from './_supabaseServerConfig.js';\nimport { shouldBreakPdfBlock, canKeepClosingTogether } from './quotePdfLayout.js';\n",'pdf layout import')
    s=replace_once(s,'    }).slice(0,8);\n','    });\n','warranty no truncation')
    s=replace_once(s,"      const proposalLines=wrapText(quote.customer_message,normal,9.2,contentW-24).slice(0,18);\n      const proposalH=34+proposalLines.length*12;\n      ensure(proposalH+14);\n      page.drawRectangle({x:margin,y:y-proposalH,width:contentW,height:proposalH,color:soft,borderColor:line,borderWidth:0.6});\n      txt('SOBRE ESTA PROPOSTA',margin+12,y-18,8.5,bold,teal);\n      let proposalY=y-38;for(const l of proposalLines){txt(l,margin+12,proposalY,9.2,normal,ink);proposalY-=12;}\n      y-=proposalH+14;\n","      const proposalLines=wrapText(quote.customer_message,normal,9.2,contentW-24);\n      let remaining=[...proposalLines];\n      let continuation=false;\n      while(remaining.length){\n        const availableLines=Math.floor((y-SAFE_BOTTOM-48)/12);\n        if(availableLines<1){newPage(true);continuation=true;continue;}\n        const chunk=remaining.splice(0,Math.max(1,availableLines));\n        const proposalH=34+chunk.length*12;\n        page.drawRectangle({x:margin,y:y-proposalH,width:contentW,height:proposalH,color:soft,borderColor:line,borderWidth:0.6});\n        txt(continuation?'SOBRE ESTA PROPOSTA · CONTINUAÇÃO':'SOBRE ESTA PROPOSTA',margin+12,y-18,8.5,bold,teal);\n        let proposalY=y-38;for(const l of chunk){txt(l,margin+12,proposalY,9.2,normal,ink);proposalY-=12;}\n        y-=proposalH+14;\n        if(remaining.length){newPage(true);continuation=true;}\n      }\n",'proposal pagination')
    s=replace_once(s,'      if (y - rowH < SAFE_BOTTOM + 205) {\n','      if (shouldBreakPdfBlock(y,rowH,SAFE_BOTTOM,12)) {\n','item calculated break')
    s=replace_once(s,"    // Grade vazia estruturada; a marca-d'água só ocupa essa área sem texto.\n    const minVisibleRows = 6;\n    let fillerRows = Math.max(0, minVisibleRows - (items || []).length);\n    while (fillerRows > 0 && y - 32 > 300) {\n      if (rowIndex % 2 === 1) page.drawRectangle({ x: margin, y: y - 25, width: contentW, height: 32, color: soft });\n      y -= 32;\n      page.drawLine({ start: { x: margin, y: y + 7 }, end: { x: tableRight, y: y + 7 }, thickness: 0.45, color: line });\n      rowIndex += 1;\n      fillerRows -= 1;\n    }\n",'', 'remove filler rows')
    s=replace_once(s,'    const leftInfoH = 35 + Math.max(1, paymentLines.length) * 11;\n    const rightInfoH = 72;\n    const notesH = noteLines.length ? 26 + noteLines.length * 11 : 0;\n    const infoCardH = Math.max(leftInfoH, rightInfoH) + notesH + 20;\n    const warrantyH=warrantyLines.length?30+warrantyLines.length*11:0;\n    const lowerBlockH = 50 + warrantyH + infoCardH + 28 + 66;\n    y -= 6;\n    if (y - lowerBlockH < SAFE_BOTTOM) newPage(true);\n','    const leftInfoH = 31 + Math.max(1, paymentLines.length) * 11;\n    const rightInfoH = 68;\n    const notesH = noteLines.length ? 24 + noteLines.length * 11 : 0;\n    const infoCardH = Math.max(leftInfoH, rightInfoH) + notesH + 12;\n    const totalBlockH = 44;\n    const warrantyH=warrantyLines.length?26+warrantyLines.length*11:0;\n    const signatureH = 58;\n    const closingGapH = 20;\n    const lowerBlockH = totalBlockH + warrantyH + infoCardH + closingGapH + signatureH;\n    y -= 4;\n    if (shouldBreakPdfBlock(y,lowerBlockH,SAFE_BOTTOM) && canKeepClosingTogether(lowerBlockH,A4[1]-88,SAFE_BOTTOM)) newPage(true);\n    else if (shouldBreakPdfBlock(y,totalBlockH,SAFE_BOTTOM)) newPage(true);\n','calculated closing block')
    s=replace_once(s,'    y -= 50;\n','    y -= totalBlockH;\n','total block height')
    s=replace_once(s,'    if(warrantyLines.length){\n','    if(warrantyLines.length){\n      ensure(30);\n','warranty page guard')
    s=replace_once(s,'      for(const lineText of warrantyLines){txt(fitText(lineText,normal,8.2,contentW),margin,y,8.2,normal,muted);y-=11;}\n      y-=8;\n','      for(const lineText of warrantyLines){\n        ensure(15);\n        for(const warrantyLine of wrapText(lineText,normal,8.2,contentW)){ensure(15);txt(warrantyLine,margin,y,8.2,normal,muted);y-=11;}\n      }\n      y-=6;\n','warranty full pagination')
    s=replace_once(s,'    // Card inferior com altura dinâmica e sem cruzar a área de assinatura.\n','    ensure(infoCardH+closingGapH+signatureH);\n    // Card inferior com altura dinâmica e sem cruzar a área de assinatura.\n','closing card guard')
    s=replace_once(s,'    y = cardBottom - 28;\n','    y = cardBottom - closingGapH;\n','closing gap')
    s=replace_once(s,'    const signatureH = 66;\n    if (y - signatureH < SAFE_BOTTOM) newPage(true);\n','    if (shouldBreakPdfBlock(y,signatureH,SAFE_BOTTOM)) newPage(true);\n','signature calculated break')
    p.write_text(s)
    (ROOT/'api/quotePdfLayout.js').write_text('export function shouldBreakPdfBlock(y, height, safeBottom = 72, reserve = 0) {\n  return Number(y) - Number(height) < Number(safeBottom) + Number(reserve);\n}\n\nexport function canKeepClosingTogether(height, continuationStartY = 753.89, safeBottom = 72) {\n  return Number(height) <= Number(continuationStartY) - Number(safeBottom);\n}\n\nexport function simulateQuotePages({\n  firstItemsY = 528,\n  continuationItemsY = 716,\n  safeBottom = 72,\n  rowHeights = [],\n  closingHeight = 206,\n} = {}) {\n  let pages = 1;\n  let y = firstItemsY;\n  for (const height of rowHeights) {\n    if (shouldBreakPdfBlock(y, height, safeBottom, 12)) { pages += 1; y = continuationItemsY; }\n    y -= height;\n  }\n  if (shouldBreakPdfBlock(y, closingHeight, safeBottom)) pages += 1;\n  return pages;\n}\n')
    (ROOT/'tests/blockers/rc1c_quote_pdf_pagination.test.mjs').write_text("import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport fs from 'node:fs';\nimport { simulateQuotePages, shouldBreakPdfBlock } from '../../api/quotePdfLayout.js';\n\nconst pdf = fs.readFileSync(new URL('../../api/quote-pdf.js', import.meta.url), 'utf8');\n\ntest('A small and B medium quotes stay one-page-first when their measured content fits', () => {\n  assert.equal(simulateQuotePages({ rowHeights:[40,40], closingHeight:206 }), 1);\n  assert.equal(simulateQuotePages({ rowHeights:[40,40,40,40,40,40], closingHeight:206 }), 1);\n});\n\ntest('C large quote naturally paginates instead of shrinking content', () => {\n  assert.ok(simulateQuotePages({ rowHeights:Array(15).fill(44), closingHeight:206 }) >= 2);\n});\n\ntest('D photos increase row height and can trigger a calculated page break', () => {\n  const withoutPhotos = simulateQuotePages({ rowHeights:Array(6).fill(40), closingHeight:206 });\n  const withPhotos = simulateQuotePages({ rowHeights:Array(6).fill(58), closingHeight:206 });\n  assert.ok(withPhotos >= withoutPhotos);\n});\n\ntest('E without photos retains compact item rows', () => {\n  assert.equal(shouldBreakPdfBlock(300, 40, 72, 12), false);\n});\n\ntest('F long commercial message is not truncated to a fixed number of lines', () => {\n  assert.doesNotMatch(pdf, /customer_message[^\\n]*slice\\(0,18\\)/);\n  assert.match(pdf, /while\\(remaining\\.length\\)/);\n  assert.match(pdf, /SOBRE ESTA PROPOSTA · CONTINUAÇÃO/);\n});\n\ntest('G warranties are not capped and are paginated with ensure guards', () => {\n  assert.doesNotMatch(pdf, /warrantyLines[\\s\\S]{0,200}slice\\(0,8\\)/);\n  assert.match(pdf, /for\\(const lineText of warrantyLines\\)/);\n  assert.match(pdf, /ensure\\(15\\)/);\n});\n\ntest('item rows no longer reserve a fixed 205px closing area or add filler rows', () => {\n  assert.doesNotMatch(pdf, /SAFE_BOTTOM \\+ 205/);\n  assert.doesNotMatch(pdf, /minVisibleRows/);\n  assert.match(pdf, /shouldBreakPdfBlock\\(y,rowH,SAFE_BOTTOM,12\\)/);\n});\n")
    pkg=json.loads((ROOT/'package.json').read_text()); verify=pkg['scripts']['verify:v2']
    extras=['tests/blockers/rc1c_mobile_work_order.test.mjs','tests/blockers/rc1c_mobile_field_workflow.test.mjs','tests/blockers/rc1c_product_primary_parity.test.mjs','tests/blockers/rc1c_quote_pdf_pagination.test.mjs']
    for x in extras:
        if x not in verify: verify += ' '+x
    pkg['scripts']['verify:v2']=verify
    (ROOT/'package.json').write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n')
    print('RC1C_MATERIALIZE_WAVE7=PASS')

if __name__=='__main__':
    wave7()
