import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Building2,CheckCircle2,Clock3,CreditCard,History,ImagePlus,Loader2,RefreshCcw,Save,ShoppingCart,Trash2,WalletCards,X}from'lucide-react';
import{carregarClientesHistoricoDB,carregarConfiguracaoVendaCampoDB,carregarHistoricoClienteDB,carregarVendasCampoDB,salvarConfiguracaoVendaCampoDB}from'../../lib/fieldSalesApi';
import{removerQrPixEmpresaDB,resolverQrPixEmpresaDB,salvarQrPixEmpresaDB}from'../../lib/fieldSalesStorage';

const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dt=v=>v?new Date(v).toLocaleString('pt-BR'):'-';

export default function FieldSalesAdminV2({companyId,companyName='Sua empresa',onClose}){
 const[tab,setTab]=useState('vendas'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const[sales,setSales]=useState([]),[clients,setClients]=useState([]),[clientId,setClientId]=useState(''),[history,setHistory]=useState([]);
 const[cfg,setCfg]=useState({pixKey:'',pixQrPath:null,allowPix:true,allowCash:true,allowCard:true}),[qrUrl,setQrUrl]=useState(null);
 const load=async()=>{setLoading(true);setError('');try{const[c,s,v]=await Promise.all([carregarConfiguracaoVendaCampoDB(companyId),carregarVendasCampoDB(companyId),carregarClientesHistoricoDB(companyId)]);setCfg(c);setSales(s);setClients(v);setQrUrl(c.pixQrPath?await resolverQrPixEmpresaDB(c.pixQrPath):null);}catch(e){setError(e?.message||'Não consegui carregar esta área.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[companyId]);
 useEffect(()=>{if(!clientId){setHistory([]);return;}carregarHistoricoClienteDB(companyId,clientId).then(setHistory).catch(e=>setError(e?.message||'Não consegui carregar o histórico.'));},[clientId,companyId]);
 const totalHoje=useMemo(()=>{const hoje=new Date().toDateString();return sales.filter(x=>new Date(x.criadoEm).toDateString()===hoje).reduce((a,b)=>a+b.total,0)},[sales]);
 const saveCfg=async()=>{setSaving(true);setError('');setOk('');try{setCfg(await salvarConfiguracaoVendaCampoDB(companyId,cfg));setOk('Configuração de recebimento salva.');}catch(e){setError(e?.message||'Não consegui salvar.');}finally{setSaving(false);}};
 const upload=async e=>{const f=e.target.files?.[0];if(!f)return;setSaving(true);try{const r=await salvarQrPixEmpresaDB(companyId,f,cfg.pixQrPath);setCfg(x=>({...x,pixQrPath:r.path}));setQrUrl(r.url);setOk('QR Code Pix atualizado.');}catch(err){setError(err?.message||'Não consegui enviar o QR Code.');}finally{setSaving(false);e.target.value='';}};
 const removeQr=async()=>{setSaving(true);try{await removerQrPixEmpresaDB(companyId,cfg.pixQrPath);setCfg(x=>({...x,pixQrPath:null}));setQrUrl(null);setOk('QR Code removido.');}catch(e){setError(e?.message||'Não consegui remover.');}finally{setSaving(false);}};
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><button onClick={onClose} className="rounded-xl border border-slate-200 p-2.5"><ArrowLeft size={18}/></button><div><h1 className="text-base font-bold">Vendas e recebimentos</h1><p className="text-xs text-slate-500">{companyName}</p></div></div><button onClick={load} className="rounded-xl border border-slate-200 p-2.5"><RefreshCcw size={17}/></button></div></header><main className="mx-auto max-w-6xl px-4 py-5 sm:px-6">
 <div className="grid grid-cols-3 rounded-2xl bg-slate-200/70 p-1">{[['vendas','Vendas'],['recebimentos','Recebimentos'],['historico','Histórico']].map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-2 py-3 text-sm font-semibold ${tab===id?'bg-white shadow-sm':'text-slate-500'}`}>{l}</button>)}</div>
 {error&&<div className="mt-4 flex gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><span className="flex-1">{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}{ok&&<div className="mt-4 flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 size={17}/><span className="flex-1">{ok}</span><button onClick={()=>setOk('')}><X size={16}/></button></div>}
 {loading?<div className="flex min-h-[40vh] items-center justify-center text-slate-500"><Loader2 className="mr-2 animate-spin" size={18}/>Carregando...</div>:<>
 {tab==='vendas'&&<section className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-400">Vendas registradas</p><p className="mt-2 text-3xl font-bold">{sales.length}</p></div><div className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-400">Recebido hoje</p><p className="mt-2 text-3xl font-bold text-teal-700">{brl(totalHoje)}</p></div></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white">{sales.length===0?<div className="p-10 text-center text-sm text-slate-500">Nenhuma venda em campo registrada.</div>:sales.map(s=><div key={s.id} className="border-b border-slate-100 p-4 last:border-0"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{s.produto}</p><p className="mt-1 text-xs text-slate-500">{s.tecnico} · {s.quantidade} un · {s.pagamento}</p>{s.cliente&&<p className="mt-1 text-xs text-slate-500">{s.cliente}{s.local?` · ${s.local}`:''}</p>}</div><strong className="text-teal-700">{brl(s.total)}</strong></div><p className="mt-2 text-[11px] text-slate-400">{dt(s.criadoEm)}</p></div>)}</div></section>}
 {tab==='recebimentos'&&<section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><WalletCards className="text-teal-700" size={20}/><h2 className="font-bold">Formas liberadas para o técnico</h2></div><div className="mt-5 space-y-3">{[['allowPix','Pix'],['allowCash','Dinheiro'],['allowCard','Cartão']].map(([k,l])=><label key={k} className="flex items-center justify-between rounded-2xl border border-slate-200 p-4"><span className="font-medium">{l}</span><input type="checkbox" checked={!!cfg[k]} onChange={e=>setCfg(x=>({...x,[k]:e.target.checked}))} className="h-5 w-5"/></label>)}</div><label className="mt-5 block"><span className="text-xs font-bold uppercase text-slate-400">Chave Pix</span><input value={cfg.pixKey} onChange={e=>setCfg(x=>({...x,pixKey:e.target.value}))} placeholder="CPF/CNPJ, telefone, e-mail ou chave aleatória" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label><button onClick={saveCfg} disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>{saving?'Salvando...':'Salvar recebimentos'}</button></div><div className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-bold">QR Code Pix da empresa</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">Envie o QR Code que o técnico deve mostrar ao cliente. A venda só é registrada depois da confirmação do pagamento.</p>{qrUrl?<img src={qrUrl} alt="QR Code Pix" className="mx-auto mt-5 h-60 w-60 rounded-2xl border border-slate-200 object-contain p-2"/>:<div className="mt-5 rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">Nenhum QR Code cadastrado.</div>}<label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold"><ImagePlus size={16}/>Enviar QR Code<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} className="hidden"/></label>{cfg.pixQrPath&&<button onClick={removeQr} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-medium text-rose-600"><Trash2 size={15}/>Remover QR Code</button>}</div></section>}
 {tab==='historico'&&<section className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Building2 className="text-teal-700" size={19}/><h2 className="font-bold">Cliente ou condomínio</h2></div><select value={clientId} onChange={e=>setClientId(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="">Selecione...</option>{clients.map(c=><option key={c.id} value={c.id}>{c.trade_name||c.name}</option>)}</select><p className="mt-3 text-xs leading-relaxed text-slate-500">Use o cadastro do condomínio como cliente. Toda OS, venda vinculada e garantia passa a formar uma linha do tempo daquele local.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><History className="text-teal-700" size={19}/><h2 className="font-bold">Histórico de prestação</h2></div>{!clientId?<div className="mt-5 rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">Escolha um cliente ou condomínio.</div>:history.length===0?<div className="mt-5 rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">Ainda não há histórico para este cadastro.</div>:<div className="mt-5 space-y-3">{history.map(h=><div key={h.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-600">{h.tipo}</span><span className="flex items-center gap-1 text-[11px] text-slate-400"><Clock3 size={12}/>{dt(h.data)}</span></div><p className="mt-2 font-bold">{h.titulo}</p><p className="mt-1 text-sm text-slate-600">{h.descricao}</p>{h.local&&<p className="mt-2 text-xs text-slate-500">Local: {h.local}</p>}</div>)}</div>}</div></section>}
 </>}</main></div>;
}
