import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,Boxes,CopyPlus,FileStack,Plus,Save,Settings2,Trash2} from 'lucide-react';
import {carregarBaseOrcamentoV2DB} from '../../lib/quoteV2Api';
import {hasBlockingReuseItems,normalizeReuseItem} from '../../lib/quoteReuseMerge';
import {novoQuoteReuseRequestId,salvarOrcamentoReutilizavelV2DB} from '../../lib/quoteReuseV2Api';

const today=()=>new Date().toISOString().slice(0,10);
const addDays=(base,days)=>{const d=new Date(`${base}T12:00:00`);d.setDate(d.getDate()+Number(days||0));return d.toISOString().slice(0,10);};
const money=(v)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function QuoteReuseEditorV2({companyId,seed,setSeed,onClose,onUseTemplate,onAddKit,onManage}){
  const [base,setBase]=useState(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(null);const requestId=useRef(null);
  if(!requestId.current){try{requestId.current=novoQuoteReuseRequestId();}catch{requestId.current=`00000000-0000-4000-8000-${String(Date.now()).slice(-12)}`;}}
  useEffect(()=>{let live=true;(async()=>{try{const b=await carregarBaseOrcamentoV2DB(companyId);if(!live)return;setBase(b);setSeed(s=>({...s,paymentTerms:s.paymentTerms||b.padroes?.condicao||'',notes:s.notes||b.padroes?.observacoes||'',validityDays:s.validityDays||b.padroes?.validadeDias||15}));}catch(e){if(live)setError(e.message||'Falha ao carregar catálogo.');}finally{if(live)setLoading(false);}})();return()=>{live=false};},[companyId,setSeed]);
  const items=(seed.items||[]).map(normalizeReuseItem);
  const subtotal=useMemo(()=>items.reduce((sum,i)=>sum+Number(i.quantity||0)*Number(i.unitPrice||0),0),[items]);
  const total=Math.max(0,subtotal-Number(seed.discount||0)+Number(seed.surcharge||0));
  const input='min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-base outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100';
  const change=(k,v)=>setSeed(s=>({...s,[k]:v}));
  const setItem=(index,patch)=>setSeed(s=>({...s,items:s.items.map((x,i)=>i===index?{...x,...patch}:x)}));
  const removeItem=(index)=>setSeed(s=>({...s,items:s.items.filter((_,i)=>i!==index)}));
  const catalog=useMemo(()=>base?[...(base.servicos||[]).filter(x=>x.ativo).map(x=>({key:`s:${x.id}`,kind:'service',serviceId:x.id,productId:null,name:x.nome,unit:x.unidade,unitPrice:x.preco,unitCost:x.custo})),...(base.produtos||[]).filter(x=>x.ativo).map(x=>({key:`p:${x.id}`,kind:'product',serviceId:null,productId:x.id,name:x.nome,unit:x.unidade,unitPrice:x.preco,unitCost:x.custo}))]:[],[base]);
  const replaceCatalog=(index,key)=>{const c=catalog.find(x=>x.key===key);if(!c)return;setItem(index,{...c,reuseKey:`replace:${c.key}:${index}`,available:true,requiresPrice:false,priceChanged:false,historicalUnitPrice:null,availabilityReason:null});};
  const addCatalog=()=>setSeed(s=>({...s,items:[...s.items,{reuseKey:`manual:${Date.now()}`,kind:'free',serviceId:null,productId:null,name:'Novo item',unit:'unidade',quantity:1,unitPrice:null,unitCost:0,available:true,requiresPrice:true}]}));
  const selectClient=(id)=>{const c=base?.clientes?.find(x=>x.id===id);setSeed(s=>({...s,clientId:id||null,address:c?.endereco||''}));};
  const save=async()=>{setError('');if(!seed.clientId){setError('Selecione um cliente.');return;}if(!items.length){setError('Adicione ao menos um item.');return;}if(hasBlockingReuseItems({items})){setError('Revise os itens indisponíveis ou sem preço antes de salvar.');return;}setSaving(true);try{const issue=today();const result=await salvarOrcamentoReutilizavelV2DB({companyId,requestId:requestId.current,row:{client_id:seed.clientId,status:'draft',issue_date:issue,valid_until:seed.validUntil||addDays(issue,seed.validityDays||15),discount:Number(seed.discount||0),surcharge:Number(seed.surcharge||0),payment_terms:seed.paymentTerms||null,notes:seed.notes||null,address:seed.address||null,service_place:seed.servicePlace||null,title:seed.title||null,customer_message:seed.customerMessage||null,description:seed.description||null,warranty_note:seed.warrantyNote||null,execution_forecast_date:seed.executionForecastDate||null,show_product_images:Boolean(seed.showProductImages),checklist_template_id:seed.checklistTemplateId||null},items});setSaved(result);}catch(e){setError(e.message||'Não foi possível salvar o orçamento.');}finally{setSaving(false);}};
  if(loading)return <div className="grid min-h-[70dvh] place-items-center p-6 text-slate-500">Preparando orçamento rápido…</div>;
  return <div className="mx-auto w-full max-w-5xl overflow-x-hidden px-3 pb-[max(7rem,env(safe-area-inset-bottom))] pt-3 sm:px-5">
    <header className="mb-4 flex flex-wrap items-center justify-between gap-2"><button onClick={onClose} className="flex min-h-11 items-center gap-2 rounded-xl border px-3"><ArrowLeft className="h-4 w-4"/>Voltar</button><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-bold text-slate-900">Orçamento rápido</h1><p className="text-sm text-slate-500">Modelo, kit ou atendimento anterior com revisão antes de salvar.</p></div></header>
    <div className="mb-4 grid gap-2 sm:grid-cols-3"><button onClick={onUseTemplate} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-900 px-3 font-semibold text-white"><FileStack className="h-4 w-4"/>Usar modelo</button><button onClick={onAddKit} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border px-3 font-semibold"><Boxes className="h-4 w-4"/>Adicionar kit</button><button onClick={onManage} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border px-3 font-semibold"><Settings2 className="h-4 w-4"/>Gerenciar</button></div>
    {seed.sourceKind==='work_order'&&<div className="mb-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><CopyPlus className="mr-2 inline h-4 w-4"/>Baseado em {seed.sourceNumber||'atendimento anterior'}. Datas, status, financeiro, garantia, relatório, evidências, assinatura e retorno não foram copiados.</div>}
    {error&&<p className="mb-4 break-words rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{saved&&<p className="mb-4 rounded-xl bg-emerald-50 p-3 font-semibold text-emerald-800">Orçamento {saved.number||''} salvo. O snapshot ficou independente do modelo/kit.</p>}
    <div className="grid gap-4 lg:grid-cols-[1fr,340px]"><main className="grid min-w-0 gap-4"><section className="grid gap-3 rounded-2xl border bg-white p-4"><h2 className="font-bold">Cliente e local</h2><label className="grid gap-1 text-sm font-medium">Cliente<select className={input} value={seed.clientId||''} onChange={e=>selectClient(e.target.value)}><option value="">Selecione</option>{(base?.clientes||[]).map(c=><option key={c.id} value={c.id}>{c.fantasia||c.nome}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Endereço atual do cliente<input className={input} value={seed.address||''} onChange={e=>change('address',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Local do serviço<input className={input} value={seed.servicePlace||''} onChange={e=>change('servicePlace',e.target.value)} placeholder="Ex.: apartamento 402, porta social"/></label></section>
      <section className="grid gap-3 rounded-2xl border bg-white p-4"><h2 className="font-bold">Proposta</h2><label className="grid gap-1 text-sm font-medium">Título<input className={input} value={seed.title||''} onChange={e=>change('title',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Mensagem ao cliente<textarea className={`${input} min-h-24 py-3`} value={seed.customerMessage||''} onChange={e=>change('customerMessage',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Descrição<textarea className={`${input} min-h-24 py-3`} value={seed.description||''} onChange={e=>change('description',e.target.value)}/></label></section>
      <section className="rounded-2xl border bg-white p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold">Itens</h2><p className="text-xs text-slate-500">Preço vindo do catálogo atual pode ser ajustado pelo owner no fluxo normal de orçamento.</p></div><button onClick={addCatalog} className="flex min-h-11 items-center gap-2 rounded-xl border px-3 text-sm font-semibold"><Plus className="h-4 w-4"/>Adicionar item</button></div><div className="grid gap-3">{items.map((item,index)=><div key={item.reuseKey||index} className={`grid min-w-0 gap-2 rounded-xl border p-3 ${item.available===false?'border-red-300 bg-red-50':'bg-slate-50'}`}><div className="flex min-w-0 items-start justify-between gap-2"><div className="min-w-0"><p className="break-words font-semibold">{item.name}</p>{item.priceChanged&&<p className="mt-1 text-xs font-medium text-amber-700">Preço atualizado: era {money(item.historicalUnitPrice)}, agora {money(item.unitPrice)}.</p>}{item.availabilityReason&&<p className="mt-1 break-words text-xs text-red-700">{item.availabilityReason}. Substitua ou remova antes de salvar.</p>}</div><button onClick={()=>removeItem(index)} className="min-h-11 min-w-11 rounded-xl border bg-white text-red-600" aria-label="Remover item"><Trash2 className="mx-auto h-4 w-4"/></button></div>{(item.available===false||item.requiresPrice)&&<select className={input} defaultValue="" onChange={e=>replaceCatalog(index,e.target.value)}><option value="">Substituir por produto/serviço ativo…</option>{catalog.map(c=><option key={c.key} value={c.key}>{c.kind==='service'?'Serviço':'Produto'} · {c.name} · {money(c.unitPrice)}</option>)}</select>}<div className="grid gap-2 sm:grid-cols-3"><label className="grid gap-1 text-xs font-medium">Quantidade<input type="number" min="0.001" step="0.001" className={input} value={item.quantity} onChange={e=>setItem(index,{quantity:e.target.value})}/></label><label className="grid gap-1 text-xs font-medium">Preço unitário<input type="number" min="0" step="0.01" className={input} value={item.unitPrice??''} onChange={e=>setItem(index,{unitPrice:e.target.value===''?null:Number(e.target.value),requiresPrice:e.target.value===''})}/></label><label className="grid gap-1 text-xs font-medium">Total<input disabled className={`${input} bg-slate-100`} value={money(Number(item.quantity||0)*Number(item.unitPrice||0))}/></label></div></div>)}{!items.length&&<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhum item ainda. Use um modelo, adicione um kit ou escolha um item.</p>}</div></section>
    </main><aside className="grid content-start gap-4"><section className="grid gap-3 rounded-2xl border bg-white p-4"><h2 className="font-bold">Condições</h2><label className="grid gap-1 text-sm font-medium">Pagamento<input className={input} value={seed.paymentTerms||''} onChange={e=>change('paymentTerms',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Observações<textarea className={`${input} min-h-20 py-3`} value={seed.notes||''} onChange={e=>change('notes',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Garantia / orientação<input className={input} value={seed.warrantyNote||''} onChange={e=>change('warrantyNote',e.target.value)}/></label><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs font-medium">Validade (dias)<input type="number" min="1" max="3650" className={input} value={seed.validityDays||15} onChange={e=>change('validityDays',e.target.value)}/></label><label className="grid gap-1 text-xs font-medium">Previsão<input type="date" className={input} value={seed.executionForecastDate||''} onChange={e=>change('executionForecastDate',e.target.value)}/></label></div>{seed.checklistTemplateId&&<p className="rounded-xl bg-sky-50 p-3 text-xs text-sky-800">Checklist associado. Ele não é criado agora; o snapshot só será gerado se este orçamento aprovado virar OS.</p>}</section><section className="grid gap-2 rounded-2xl bg-slate-900 p-4 text-white"><div className="flex justify-between text-sm"><span>Subtotal</span><span>{money(subtotal)}</span></div><label className="grid grid-cols-[1fr,120px] items-center gap-2 text-sm"><span>Desconto</span><input type="number" min="0" step="0.01" className="min-h-11 rounded-xl border border-slate-600 bg-slate-800 px-3 text-right text-base" value={seed.discount||0} onChange={e=>change('discount',e.target.value)}/></label><label className="grid grid-cols-[1fr,120px] items-center gap-2 text-sm"><span>Acréscimo</span><input type="number" min="0" step="0.01" className="min-h-11 rounded-xl border border-slate-600 bg-slate-800 px-3 text-right text-base" value={seed.surcharge||0} onChange={e=>change('surcharge',e.target.value)}/></label><div className="mt-1 flex justify-between border-t border-slate-700 pt-3 text-lg font-bold"><span>Total</span><span>{money(total)}</span></div><button disabled={saving||Boolean(saved)} onClick={save} className="mt-2 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 font-bold text-slate-950 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Salvando…':saved?'Salvo':'Salvar orçamento'}</button></section></aside></div>
  </div>;
}
