import React from 'react';
import {
  ArrowLeft, Boxes, ChevronRight, CircleDollarSign, ClipboardList, FileText, HardHat,
  LockKeyhole, PackageCheck, ShieldCheck, ShoppingCart, Sparkles, Wrench,
} from 'lucide-react';

const MODULES = [
  { id:'orcamentos', ownerOnly:true, icon:ClipboardList, title:'Gestão de orçamentos', description:'Pipeline, status, margem, duplicação e conversão segura de orçamento aprovado em uma única OS.', badge:'Comercial' },
  { id:'orcamento-ia', ownerOnly:true, icon:Sparkles, title:'Novo orçamento com voz e IA', description:'Fale ou digite o pedido, revise ambiguidades, preços, custo e margem antes de salvar.', badge:'IA assistida' },
  { id:'produtos', ownerOnly:true, icon:Boxes, title:'Produtos e estoque', description:'Catálogo, custo, preço, margem, estoque mínimo, fotos e movimentações.', badge:'Proprietário' },
  { id:'compras', ownerOnly:true, icon:ShoppingCart, title:'Compras', description:'Fornecedor, itens, vencimento e entrada automática no estoque sem duplicar retries.', badge:'Estoque' },
  { id:'venda-os', ownerOnly:false, icon:PackageCheck, title:'Venda dentro da OS', description:'Adicionar produto durante o atendimento e baixar o estoque automaticamente.', badge:'Campo' },
  { id:'garantias', ownerOnly:true, icon:ShieldCheck, title:'Garantias', description:'Registrar garantias manuais e acompanhar cobertura por cliente, produto e serviço.', badge:'Pós-venda' },
  { id:'contratos', ownerOnly:true, icon:Wrench, title:'Preventivas e contratos', description:'Contratos recorrentes, próximas visitas, cobrança e geração segura dos ciclos.', badge:'Recorrência' },
  { id:'financeiro', ownerOnly:true, icon:CircleDollarSign, title:'Financeiro', description:'Faturado, recebido, atrasos, projeção de caixa e rentabilidade real por OS.', badge:'Proprietário' },
];

export default function WorkspaceV2Home({ companyName='Sua empresa', owner=false, onOpen, onClose }) {
  const modules=MODULES.filter(m=>owner||!m.ownerOnly);
  return <div className="min-h-screen bg-slate-950 text-white">
    <header className="border-b border-white/10 bg-slate-950/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><button onClick={onClose} className="rounded-xl border border-white/10 bg-white/5 p-2.5 text-slate-300 transition hover:bg-white/10" aria-label="Voltar"><ArrowLeft size={19}/></button><div><div className="flex items-center gap-2"><h1 className="text-base font-bold tracking-tight">ZiisTec Stack V2</h1><span className="rounded-full bg-emerald-400/10 px-2 py-0.5 text-[10px] font-bold text-emerald-300">PREVIEW</span></div><p className="mt-0.5 truncate text-xs text-slate-400">{companyName}</p></div></div><div className="hidden items-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/5 px-3 py-2 text-xs font-semibold text-emerald-300 sm:flex"><LockKeyhole size={15}/>Branch segura</div></div></header>

    <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6 sm:py-10">
      <section className="overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-emerald-400/10 via-white/[0.035] to-transparent p-6 sm:p-8"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-[11px] font-bold uppercase tracking-wide text-emerald-300"><Sparkles size={13}/>Nova operação</div><h2 className="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">Menos tela, mais serviço em campo.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-300">Esta é a nova área do ZiisTec. Os módulos abaixo estão sendo ligados ao backend V2 com isolamento por empresa e permissões reais no banco, não apenas botões escondidos na interface.</p></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Perfil</p><p className="mt-1 text-sm font-bold">{owner?'Proprietário':'Técnico'}</p></div><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Segurança</p><p className="mt-1 text-sm font-bold text-emerald-300">RLS + custos privados</p></div><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Publicação</p><p className="mt-1 text-sm font-bold text-amber-300">Homologação antes da main</p></div></div></section>

      <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-400">Módulos V2</p><h3 className="mt-1 text-lg font-bold">Escolha onde trabalhar</h3></div><span className="text-xs text-slate-500">{modules.length} disponível{modules.length===1?'':'eis'}</span></div><div className="grid gap-3 md:grid-cols-2">{modules.map(({id,icon:Icon,title,description,badge})=><button key={id} onClick={()=>onOpen(id)} className="group flex items-start gap-4 rounded-3xl border border-white/10 bg-white/[0.045] p-5 text-left transition hover:border-emerald-400/30 hover:bg-emerald-400/[0.07]"><div className="rounded-2xl border border-white/10 bg-white/[0.05] p-3 text-emerald-300 transition group-hover:border-emerald-400/20 group-hover:bg-emerald-400/10"><Icon size={21}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="text-sm font-bold text-white">{title}</h4><span className="rounded-full bg-white/[0.06] px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide text-slate-400">{badge}</span></div><p className="mt-2 text-xs leading-relaxed text-slate-400">{description}</p></div><ChevronRight className="mt-1 shrink-0 text-slate-600 transition group-hover:translate-x-0.5 group-hover:text-emerald-300" size={18}/></button>)}</div></section>

      <section className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-400/10 p-2.5 text-emerald-300"><FileText size={18}/></div><div><p className="text-sm font-bold">Orçamento → OS protegido</p><p className="mt-0.5 text-xs text-slate-500">A conversão V2 exige aprovação e a migration 0057 impede OS duplicada por retry ou duplo clique.</p></div></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-sky-400/10 p-2.5 text-sky-300"><HardHat size={18}/></div><div><p className="text-sm font-bold">Visão do técnico protegida</p><p className="mt-0.5 text-xs text-slate-500">Custos, margem, fornecedor e financeiro não fazem parte do payload de campo.</p></div></div></div></section>

      <p className="mt-8 text-center text-[11px] leading-relaxed text-slate-600">Preview da branch product-v2-review. As migrations V2 permanecem fora do banco de produção até a homologação completa.</p>
    </main>
  </div>;
}
