import React,{useEffect,useMemo,useState} from 'react';
import {CopyPlus,Search,X} from 'lucide-react';
import WorkOrderMemoryBaseV2 from './WorkOrderMemoryBaseV2';
import {listarAtendimentosReutilizaveisV2DB} from '../../lib/quoteReuseV2Api';

export default function WorkOrderMemoryV2(props){
  const [open,setOpen]=useState(false);const [rows,setRows]=useState([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(!open||!props.owner)return;let live=true;setLoading(true);listarAtendimentosReutilizaveisV2DB(props.companyId).then(x=>{if(live)setRows(x||[])}).catch(e=>{if(live)setError(e.message||'Falha ao carregar atendimentos.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false};},[open,props.companyId,props.owner]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>!q||`${r.number||''} ${r.client_name||''} ${r.service_place||''} ${r.request||''}`.toLowerCase().includes(q));},[rows,query]);
  const reuse=id=>{const url=new URL(window.location.href);url.searchParams.set('v2','orcamento-ia');url.searchParams.set('source_wo',id);window.location.assign(`${url.pathname}${url.search}${url.hash}`);};
  return <div className="relative"><WorkOrderMemoryBaseV2 {...props}/>{props.owner&&<button onClick={()=>setOpen(true)} className="fixed bottom-[max(5.5rem,env(safe-area-inset-bottom))] right-3 z-40 flex min-h-12 max-w-[calc(100vw-1.5rem)] items-center gap-2 rounded-2xl bg-slate-900 px-4 font-semibold text-white shadow-xl sm:right-5"><CopyPlus className="h-4 w-4"/><span className="break-words text-sm">Criar orçamento baseado em atendimento</span></button>}
    {open&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label="Reutilizar atendimento"><div className="flex w-full max-w-3xl flex-col overflow-hidden rounded-t-3xl bg-white sm:rounded-3xl max-h-[min(92dvh,780px)]"><header className="flex min-h-14 items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold">Atendimentos concluídos</h2><p className="text-sm text-slate-500">Cria uma nova proposta para revisão, sem copiar financeiro nem pós-venda.</p></div><button onClick={()=>setOpen(false)} className="min-h-11 min-w-11 rounded-xl border" aria-label="Fechar"><X className="mx-auto h-5 w-5"/></button></header><div className="border-b p-4"><label className="relative block"><Search className="absolute left-3 top-3.5 h-5 w-5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar OS, cliente ou local" className="min-h-12 w-full rounded-xl border pl-10 pr-3 text-base outline-none focus:border-emerald-500"/></label></div><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 pb-[max(1rem,env(safe-area-inset-bottom))]">{loading&&<p className="py-8 text-center text-slate-500">Carregando…</p>}{error&&<p className="break-words rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="grid gap-3">{filtered.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="mb-3 min-w-0"><p className="break-words font-semibold">{r.number} · {r.client_name}</p><p className="break-words text-sm text-slate-500">{r.service_place||r.request||'Atendimento concluído'}</p></div><button onClick={()=>reuse(r.id)} className="min-h-12 w-full rounded-xl bg-emerald-600 px-3 text-sm font-bold text-white">Criar orçamento baseado neste atendimento</button></article>)}{!loading&&!error&&!filtered.length&&<p className="py-8 text-center text-slate-500">Nenhum atendimento concluído encontrado.</p>}</div></div></div></div>}
  </div>;
}

/* MOBILE HOMOLOGATION · work order memory · wave 3 */
/* MOBILE HOMOLOGATION · history lookup · wave 6 */
/* FIELD WORKFLOW V1 · wave 4a · quote reuse wrappers */
