import React,{useEffect,useMemo,useState} from 'react';
import {Archive,Plus,Save,Trash2,X} from 'lucide-react';
import {carregarBaseOrcamentoV2DB} from '../lib/quoteV2Api';
import {carregarChecklistTemplatesV2DB} from '../lib/checklistReturnV2Api';
import {listarKitsOrcamentoV2DB,listarModelosOrcamentoV2DB,salvarKitOrcamentoV2DB,salvarModeloOrcamentoV2DB} from '../lib/quoteReuseV2Api';

const blank=(kind)=>({id:null,name:'',description:'',quoteTitle:'',customerMessage:'',notes:'',paymentTerms:'',warrantyNote:'',validityDays:'15',forecastDays:'',checklistTemplateId:'',active:true,items:[],kind});
const itemFrom=(x)=>({serviceId:x.service_id||null,productId:x.product_id||null,quantity:Number(x.quantity||1),notes:x.notes||''});
const formFrom=(r,kind)=>({id:r.id,name:r.name||'',description:r.description||'',quoteTitle:r.quote_title||'',customerMessage:r.customer_message||'',notes:r.notes||'',paymentTerms:r.payment_terms||'',warrantyNote:r.warranty_note||'',validityDays:r.validity_days??'',forecastDays:r.execution_forecast_days??'',checklistTemplateId:r.checklist_template_id||'',active:r.active!==false,items:(r.items||[]).map(itemFrom),kind});

export default function QuoteReuseAdmin({companyId,onClose}){
  const [tab,setTab]=useState('template');const [rows,setRows]=useState([]);const [base,setBase]=useState({servicos:[],produtos:[]});const [checks,setChecks]=useState([]);const [form,setForm]=useState(blank('template'));const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const reload=async(kind=tab)=>{setLoading(true);setError('');try{const [data,b,c]=await Promise.all([kind==='kit'?listarKitsOrcamentoV2DB(companyId):listarModelosOrcamentoV2DB(companyId),carregarBaseOrcamentoV2DB(companyId),carregarChecklistTemplatesV2DB(companyId)]);setRows(data||[]);setBase(b);setChecks((c||[]).filter(x=>x.active));}catch(e){setError(e.message||'Falha ao carregar.');}finally{setLoading(false);}};
  useEffect(()=>{reload(tab);},[companyId,tab]);
  const catalog=useMemo(()=>[...(base.servicos||[]).filter(x=>x.ativo).map(x=>({key:`s:${x.id}`,label:`Serviço · ${x.nome}`,serviceId:x.id,productId:null})),...(base.produtos||[]).filter(x=>x.ativo).map(x=>({key:`p:${x.id}`,label:`Produto · ${x.nome}`,serviceId:null,productId:x.id}))],[base]);
  const change=(k,v)=>setForm(f=>({...f,[k]:v}));
  const chooseRow=(r)=>setForm(formFrom(r,tab));
  const addItem=()=>setForm(f=>({...f,items:[...f.items,{serviceId:null,productId:null,quantity:1,notes:''}]}));
  const setItem=(index,patch)=>setForm(f=>({...f,items:f.items.map((x,i)=>i===index?{...x,...patch}:x)}));
  const save=async(active=form.active)=>{setSaving(true);setError('');try{if(!form.name.trim())throw new Error('Informe o nome.');if(form.items.some(x=>!x.serviceId&&!x.productId))throw new Error('Selecione o produto/serviço de cada item.');if(tab==='template')await salvarModeloOrcamentoV2DB({companyId,id:form.id,payload:{name:form.name,quote_title:form.quoteTitle,customer_message:form.customerMessage,description:form.description,notes:form.notes,payment_terms:form.paymentTerms,warranty_note:form.warrantyNote,validity_days:form.validityDays||null,execution_forecast_days:form.forecastDays===''?null:form.forecastDays,checklist_template_id:form.checklistTemplateId||null,active},items:form.items});else await salvarKitOrcamentoV2DB({companyId,id:form.id,payload:{name:form.name,description:form.description,active},items:form.items});setForm(blank(tab));await reload(tab);}catch(e){setError(e.message||'Não foi possível salvar.');}finally{setSaving(false);}};
  const input='min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base outline-none focus:border-emerald-500';
  return <div className="fixed inset-0 z-[90] flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label="Gerenciar modelos e kits"><div className="flex w-full max-w-5xl flex-col overflow-hidden rounded-t-3xl bg-white sm:rounded-3xl max-h-[min(94dvh,900px)]">
    <header className="flex min-h-14 items-center justify-between gap-3 border-b px-4 py-3"><div><h2 className="text-lg font-bold">Modelos e kits</h2><p className="text-sm text-slate-500">Somente o proprietário administra estes atalhos.</p></div><button onClick={onClose} className="min-h-11 min-w-11 rounded-xl border" aria-label="Fechar"><X className="mx-auto h-5 w-5"/></button></header>
    <div className="flex gap-2 border-b p-3">{['template','kit'].map(k=><button key={k} onClick={()=>{setTab(k);setForm(blank(k));}} className={`min-h-11 flex-1 rounded-xl px-3 font-semibold ${tab===k?'bg-slate-900 text-white':'bg-slate-100 text-slate-700'}`}>{k==='template'?'Modelos':'Kits'}</button>)}</div>
    <div className="grid min-h-0 flex-1 md:grid-cols-[280px,1fr]"><aside className="max-h-56 overflow-y-auto border-b p-3 md:max-h-none md:border-b-0 md:border-r"><button onClick={()=>setForm(blank(tab))} className="mb-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 px-3 font-semibold text-white"><Plus className="h-4 w-4"/>Novo</button>{loading?<p className="p-3 text-sm text-slate-500">Carregando…</p>:rows.map(r=><button key={r.id} onClick={()=>chooseRow(r)} className="mb-2 min-h-11 w-full rounded-xl border p-3 text-left"><span className="block break-words font-medium">{r.name}</span><span className="text-xs text-slate-500">{r.active?'Ativo':'Arquivado'} · {(r.items||[]).length} item(ns)</span></button>)}</aside>
      <main className="min-h-0 overflow-y-auto overscroll-contain p-4 pb-[max(1rem,env(safe-area-inset-bottom))]"><div className="mx-auto grid max-w-2xl gap-4">
        {error&&<p className="break-words rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
        <label className="grid gap-1 text-sm font-medium">Nome<input className={input} value={form.name} onChange={e=>change('name',e.target.value)} maxLength={200}/></label>
        {tab==='template'&&<><label className="grid gap-1 text-sm font-medium">Título do orçamento<input className={input} value={form.quoteTitle} onChange={e=>change('quoteTitle',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Mensagem ao cliente<textarea className={`${input} min-h-24 py-3`} value={form.customerMessage} onChange={e=>change('customerMessage',e.target.value)}/></label></>}
        <label className="grid gap-1 text-sm font-medium">Descrição<textarea className={`${input} min-h-24 py-3`} value={form.description} onChange={e=>change('description',e.target.value)}/></label>
        {tab==='template'&&<><label className="grid gap-1 text-sm font-medium">Observações<textarea className={`${input} min-h-20 py-3`} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Condições de pagamento<input className={input} value={form.paymentTerms} onChange={e=>change('paymentTerms',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Garantia / orientação<input className={input} value={form.warrantyNote} onChange={e=>change('warrantyNote',e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Validade sugerida (dias)<input type="number" min="1" max="3650" className={input} value={form.validityDays} onChange={e=>change('validityDays',e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Previsão sugerida (+ dias)<input type="number" min="0" max="3650" className={input} value={form.forecastDays} onChange={e=>change('forecastDays',e.target.value)}/></label></div><label className="grid gap-1 text-sm font-medium">Checklist relacionado<select className={input} value={form.checklistTemplateId} onChange={e=>change('checklistTemplateId',e.target.value)}><option value="">Sem checklist</option>{checks.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}
        <section className="rounded-2xl border p-3"><div className="mb-3 flex items-center justify-between gap-2"><div><h3 className="font-semibold">Itens</h3><p className="text-xs text-slate-500">Referências e quantidades. Preço é resolvido pelo catálogo ao usar.</p></div><button onClick={addItem} className="min-h-11 rounded-xl border px-3 text-sm font-semibold">Adicionar</button></div><div className="grid gap-3">{form.items.map((item,index)=><div key={index} className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-[1fr,100px,44px]"><select className={input} value={item.serviceId?`s:${item.serviceId}`:item.productId?`p:${item.productId}`:''} onChange={e=>{const c=catalog.find(x=>x.key===e.target.value);setItem(index,{serviceId:c?.serviceId||null,productId:c?.productId||null});}}><option value="">Selecione</option>{catalog.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select><input aria-label="Quantidade" type="number" min="0.001" step="0.001" className={input} value={item.quantity} onChange={e=>setItem(index,{quantity:e.target.value})}/><button aria-label="Remover item" onClick={()=>setForm(f=>({...f,items:f.items.filter((_,i)=>i!==index)}))} className="min-h-11 min-w-11 rounded-xl border text-red-600"><Trash2 className="mx-auto h-4 w-4"/></button></div>)}</div></section>
        <div className="sticky bottom-0 grid gap-2 bg-white/95 py-3 sm:grid-cols-2">{form.id&&form.active&&<button disabled={saving} onClick={()=>save(false)} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-amber-300 font-semibold text-amber-800"><Archive className="h-4 w-4"/>Arquivar</button>}<button disabled={saving} onClick={()=>save(form.active)} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Salvando…':'Salvar'}</button></div>
      </div></main></div></div></div>;
}
