import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const file = 'src/legacy/ZiisTecApp.jsx';
const PRE = 'ce1523f036d2db33d6bfe24631907ef2bf3d2aca144366c1fc64fbdb0a5e9104';
const POST = '91edc5619d96a8ece1b6172b084d2426a128baa1a7334c3c5ebe2f6cb5bdefd4';
const hash = (v) => createHash('sha256').update(v).digest('hex');
let s = readFileSync(file, 'utf8');
if (hash(s) !== PRE) throw new Error(`Round 3.1 expected Round 3 source ${PRE}, got ${hash(s)}`);

function once(re, value, label) {
  const matches = [...s.matchAll(new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g'))];
  if (matches.length !== 1) throw new Error(`Round 3.1 ${label}: expected 1 match, got ${matches.length}`);
  s = s.replace(re, value);
}

once(/(salvarOSDB, atualizarOSDB, finalizarOSDB, resolverPrecificacaoOSDB, baixarLancamentoDB, salvarLancamentoDB, atualizarStatusOrcamentoDB,\n)(\} from "\.\.\/lib\/dataApi";)/, '$1  excluirRegistroDB,\n$2', 'dataApi import');
once(/    danger: "text-rose-700 hover:bg-rose-50",\n/, '    danger: "text-rose-700 hover:bg-rose-50",\n    dangerSolid: "bg-rose-600 text-white hover:bg-rose-700",\n', 'danger button variant');
once(/<Btn variant="dark" onClick=\{\(\) => \{ estado\.acao\(\); onClose\(\); \}\}>\{estado\.confirmar\}<\/Btn>/, '<Btn variant={estado.perigo ? "dangerSolid" : "dark"} onClick={() => { estado.acao(); onClose(); }}>{estado.confirmar}</Btn>', 'danger confirm');
once(/const \[drawer, setDrawer\] = useState\(false\);\n  const \[busca, setBusca\]/, 'const [drawer, setDrawer] = useState(false);\n  const [menuExpandido, setMenuExpandido] = useState(false);\n  const [busca, setBusca]', 'sidebar state');

// Clientes arquivados continuam carregados para documentos históricos, mas somem de buscas e novos vínculos.
s = s.replace('clientes.map((c) => ({ id: c.id, nome: c.fantasia || c.nome }))', 'clientes.filter((c) => !c.excluidoEm).map((c) => ({ id: c.id, nome: c.fantasia || c.nome }))');
once(/const rc = permitido\("clientes"\) \? clientes\.filter\(\(c\) => bate\(/, 'const rc = permitido("clientes") ? clientes.filter((c) => !c.excluidoEm && bate(', 'global client search');
once(/const lista = clientes\.filter\(\(c\) => semAcento\(/, 'const lista = clientes.filter((c) => !c.excluidoEm && semAcento(', 'client list');
once(/\? clientes\.filter\(\(c\) => semAcento\(c\.fantasia \|\| c\.nome\)/, '? clientes.filter((c) => !c.excluidoEm && semAcento(c.fantasia || c.nome)', 'AI client suggestion');
s = s.replaceAll('{clientes.map((x) => <option key={x.id} value={x.id}>{x.fantasia || x.nome}</option>)}', '{clientes.filter((x) => !x.excluidoEm).map((x) => <option key={x.id} value={x.id}>{x.fantasia || x.nome}</option>)}');
s = s.replaceAll('{clientes.map((c) => <option key={c.id} value={c.id}>{c.fantasia || c.nome}</option>)}', '{clientes.filter((c) => !c.excluidoEm).map((c) => <option key={c.id} value={c.id}>{c.fantasia || c.nome}</option>)}');

const deleteBlock = `  const excluirRegistro = (tipo, id, nome, aoExcluir) => {\n    if (papel !== "proprietario") { aviso("Somente o proprietário pode excluir registros."); return; }\n    const rotulos = { cliente:"cliente", servico:"serviço", produto:"produto", orcamento:"orçamento", os:"ordem de serviço", compra:"compra", financeiro:"lançamento", garantia:"garantia" };\n    const rotulo = rotulos[tipo] || "registro";\n    setConfirmar({\n      titulo: \`Excluir \${rotulo}?\`,\n      texto: \`\${nome || "Este registro"} deixará de aparecer nas listas ativas. Os vínculos históricos necessários para documentos, financeiro e auditoria serão preservados.\`,\n      confirmar: "Excluir", perigo: true,\n      acao: async () => {\n        try {\n          if (real) { await excluirRegistroDB(tipo, id, empresaId); await recarregarDados(); }\n          else {\n            const agora = new Date().toISOString();\n            if (tipo === "cliente") setClientes((ls) => ls.map((x) => x.id === id ? { ...x, excluidoEm: agora } : x));\n            if (tipo === "servico") setServicos((ls) => ls.filter((x) => x.id !== id));\n            if (tipo === "produto") setProdutos((ls) => ls.filter((x) => x.id !== id));\n            if (tipo === "orcamento") setOrcamentos((ls) => ls.filter((x) => x.id !== id));\n            if (tipo === "os") setOrdens((ls) => ls.filter((x) => x.id !== id));\n            if (tipo === "compra") setCompras((ls) => ls.filter((x) => x.id !== id));\n            if (tipo === "financeiro") setLancamentos((ls) => ls.filter((x) => x.id !== id));\n            if (tipo === "garantia") setGarantias((ls) => ls.filter((x) => x.id !== id));\n          }\n          aoExcluir?.(); aviso(\`\${rotulo.charAt(0).toUpperCase() + rotulo.slice(1)} excluído com segurança.\`);\n        } catch (e) { aviso(mensagemErro(e)); }\n      },\n    });\n  };\n\n`;
once(/(  const abrirGarantia = \(id\) => \{[^\n]+\};\n\n)(  const proxNumero)/, `$1${deleteBlock}$2`, 'delete action');
once(/pedirConfirmacao: setConfirmar,\n  \};/, 'pedirConfirmacao: setConfirmar, excluirRegistro,\n  };', 'delete prop');

// Sidebar: no tablet o usuário pode abrir/recolher os nomes; desktop permanece largo.
once(/rail && "lg:px-5 px-0 lg:justify-start justify-center"/, 'rail && !menuExpandido && "md:px-0 md:justify-center lg:px-5 lg:justify-start"', 'brand align');
once(/rail && "hidden lg:block"\)\}>ZiisTec/, 'rail && !menuExpandido && "hidden lg:block")}>ZiisTec', 'brand label');
once(/rail && "lg:justify-start justify-center",/, 'rail && !menuExpandido && "md:justify-center lg:justify-start",', 'nav align');
once(/<span className=\{rail \? "hidden lg:inline" : ""\}>\{n\.label\}<\/span>/, '<span className={rail && !menuExpandido ? "hidden lg:inline" : ""}>{n.label}</span>', 'nav labels');
once(/rail && "hidden lg:block"\)\}>\n      <div className="flex items-center gap-3 rounded-xl/, 'rail && !menuExpandido && "hidden lg:block")}>\n      <div className="flex items-center gap-3 rounded-xl', 'company card');
const aside = `      <aside className={cx("zt-nao-imprime hidden md:flex fixed inset-y-0 left-0 z-30 bg-slate-900 flex-col transition-[width] duration-200", menuExpandido ? "md:w-[248px]" : "md:w-[72px] lg:w-[248px]")}>\n        <Marca rail />\n        <button onClick={() => setMenuExpandido((v) => !v)} aria-label={menuExpandido ? "Recolher menu" : "Expandir menu"} title={menuExpandido ? "Recolher menu" : "Mostrar nomes das funções"}\n          className={cx("hidden md:flex lg:hidden absolute -right-3 top-[78px] w-7 h-7 rounded-full bg-white shadow ring-1 ring-slate-200 items-center justify-center text-slate-600 hover:text-slate-900", ring)}>\n          <ChevronRight className={cx("w-4 h-4 transition-transform", menuExpandido && "rotate-180")} />\n        </button>\n        <Nav rail /><Empresa rail />\n      </aside>`;
once(/      <aside className="zt-nao-imprime hidden md:flex fixed inset-y-0 left-0 z-30 md:w-\[72px\] lg:w-\[248px\] bg-slate-900 flex-col">\n        <Marca rail \/><Nav rail \/><Empresa rail \/>\n      <\/aside>/, aside, 'sidebar toggle');
once(/<main className="md:pl-\[72px\] lg:pl-\[248px\]">/, '<main className={cx("transition-[padding] duration-200", menuExpandido ? "md:pl-[248px]" : "md:pl-[72px] lg:pl-[248px]")}>', 'main padding');

// Exclusão visível e owner-only nos módulos.
once(/const \{ clientes, orcamentos, ordens, lancamentos, garantias, salvarCliente, clienteAberto, setClienteAberto, abrirOrc, abrirOS, abrirGarantia, setTela, setOrcamentoAberto, empresaId, real, aviso \} = p;/, 'const { clientes, orcamentos, ordens, lancamentos, garantias, salvarCliente, clienteAberto, setClienteAberto, abrirOrc, abrirOS, abrirGarantia, setTela, setOrcamentoAberto, empresaId, real, aviso, excluirRegistro, papel } = p;', 'client props');
once(/<Btn variant="soft" size="sm" icon=\{Pencil\} onClick=\{\(\) => setForm\(c\)\}>Editar<\/Btn>\n            <Btn size="sm" icon=\{FileText\}/, '<Btn variant="soft" size="sm" icon={Pencil} onClick={() => setForm(c)}>Editar</Btn>\n            {papel === "proprietario" && <Btn variant="danger" size="sm" icon={Trash2} onClick={() => excluirRegistro("cliente", c.id, c.fantasia || c.nome, () => setClienteAberto(null))}>Excluir</Btn>}\n            <Btn size="sm" icon={FileText}', 'client delete');
once(/<div className="flex gap-2">\n            <Btn variant="soft" size="sm" icon=\{Pencil\} onClick=\{\(\) => setForm\(c\)\}/, '<div className="flex gap-2 flex-wrap">\n            <Btn variant="soft" size="sm" icon={Pencil} onClick={() => setForm(c)}', 'client action wrap');
once(/\{c\.tipo === "PJ" \? c\.nome : "Pessoa física"\} · \{c\.documento\}<\/p>/, '{c.tipo === "PJ" ? c.nome : "Pessoa física"} · {c.documento}{c.excluidoEm ? " · arquivado" : ""}</p>', 'archived client marker');
once(/function Catalogo\(\{ servicos, produtos, salvarServico, salvarProduto \}\)/, 'function Catalogo({ servicos, produtos, salvarServico, salvarProduto, excluirRegistro, papel })', 'catalog props');
once(/footer=\{<><Btn variant="ghost" onClick=\{\(\) => setFormS\(null\)\}>Cancelar<\/Btn>/, 'footer={<>{formS.id && papel === "proprietario" && <Btn variant="danger" icon={Trash2} onClick={() => excluirRegistro("servico", formS.id, formS.nome, () => setFormS(null))}>Excluir</Btn>}<span className="flex-1" /><Btn variant="ghost" onClick={() => setFormS(null)}>Cancelar</Btn>', 'service delete');
once(/footer=\{<><Btn variant="ghost" onClick=\{\(\) => setFormP\(null\)\}>Cancelar<\/Btn>/, 'footer={<>{formP.id && papel === "proprietario" && <Btn variant="danger" icon={Trash2} onClick={() => excluirRegistro("produto", formP.id, formP.nome, () => setFormP(null))}>Excluir</Btn>}<span className="flex-1" /><Btn variant="ghost" onClick={() => setFormP(null)}>Cancelar</Btn>', 'product delete');
once(/const \{ orc, cliente, empresa, mudarStatusOrc, duplicarOrcamento, gerarOS, setOrcamentoAberto, aviso, pedirConfirmacao \} = p;/, 'const { orc, cliente, empresa, mudarStatusOrc, duplicarOrcamento, gerarOS, setOrcamentoAberto, aviso, pedirConfirmacao, excluirRegistro, papel } = p;', 'quote props');
once(/(<Btn variant="soft" size="sm" icon=\{Pencil\} onClick=\{\(\) => setEditando\(true\)\}>Editar<\/Btn>)/, '$1\n            {papel === "proprietario" && <Btn variant="danger" size="sm" icon={Trash2} onClick={() => excluirRegistro("orcamento", orc.id, `${orc.numero} — ${c?.fantasia || c?.nome || "Cliente"}`, () => setOrcamentoAberto(null))}>Excluir</Btn>}', 'quote delete');
once(/papel, resolverPrecificacao \} = p;/, 'papel, resolverPrecificacao, excluirRegistro } = p;', 'OS props');
once(/(\{acoes\.map\(\(a\) => <Btn[^\n]+\n)(          \{os\.status !== "concluida")/, '$1          {papel === "proprietario" && <Btn size="sm" variant="danger" icon={Trash2} onClick={() => excluirRegistro("os", os.id, os.numero, () => setOsAberta(null))}>Excluir OS</Btn>}\n$2', 'OS delete');
once(/function Compras\(\{ compras, produtos, lancamentos, salvarCompra, compraAberta, setCompraAberta, setTela, pedirConfirmacao \}\)/, 'function Compras({ compras, produtos, lancamentos, salvarCompra, compraAberta, setCompraAberta, setTela, pedirConfirmacao, excluirRegistro, papel })', 'purchase props');
once(/<Btn variant="soft" size="sm" icon=\{Pencil\} onClick=\{\(\) => setForm\(\{ \.\.\.c, jaPago: Boolean\(lanc\?\.pago\) \}\)\}>Editar<\/Btn>/, '<div className="flex gap-2 flex-wrap"><Btn variant="soft" size="sm" icon={Pencil} onClick={() => setForm({ ...c, jaPago: Boolean(lanc?.pago) })}>Editar</Btn>{papel === "proprietario" && <Btn variant="danger" size="sm" icon={Trash2} onClick={() => excluirRegistro("compra", c.id, `${c.numero} · ${c.fornecedor}`, () => setCompraAberta(null))}>Excluir</Btn>}</div>', 'purchase delete');
once(/function Financeiro\(\{ lancamentos, setLancamentos, baixar, clientes, ordens, aviso, pedirConfirmacao, abrirOS, abrirCompra, compras, real, empresaId, empresa: empresaDados \}\)/, 'function Financeiro({ lancamentos, setLancamentos, baixar, clientes, ordens, aviso, pedirConfirmacao, abrirOS, abrirCompra, compras, real, empresaId, empresa: empresaDados, excluirRegistro, papel })', 'finance props');
once(/(onClick=\{\(\) => setRecibo\(l\)\}>\{l\.pago \? "Recibo" : "Cobrança"\}<\/Btn>\s*\)\})/, '$1\n                {papel === "proprietario" && <Btn size="sm" variant="danger" icon={Trash2} title="Excluir lançamento" ariaLabel={`Excluir ${l.descricao}`} onClick={() => excluirRegistro("financeiro", l.id, l.descricao)}>Excluir</Btn>}', 'finance delete');
once(/function Garantias\(\{ garantias, ordens, clientes, nomeCliente, garantiaAberta, setGarantiaAberta, abrirOS, abrirCliente, abrirAtendimentoGarantia, produtos, empresaId, real, aviso \}\)/, 'function Garantias({ garantias, ordens, clientes, nomeCliente, garantiaAberta, setGarantiaAberta, abrirOS, abrirCliente, abrirAtendimentoGarantia, produtos, empresaId, real, aviso, excluirRegistro, papel })', 'warranty props');
once(/\{st\.ativa && <Btn icon=\{ShieldCheck\} onClick=\{\(\) => \{ setRelatoProblema\(""\); setAcionando\(true\); \}\}>Abrir atendimento em garantia<\/Btn>\}/, '<div className="flex gap-2 flex-wrap">{papel === "proprietario" && <Btn variant="danger" icon={Trash2} onClick={() => excluirRegistro("garantia", g.id, g.descricao, () => setGarantiaAberta(null))}>Excluir</Btn>}{st.ativa && <Btn icon={ShieldCheck} onClick={() => { setRelatoProblema(""); setAcionando(true); }}>Abrir atendimento em garantia</Btn>}</div>', 'warranty delete');

// Agenda não é outro registro: remover da agenda apenas limpa data/hora da OS.
once(/function Agenda\(\{ ordens, nomeCliente, abrirOS, agendarOS, empresa, equipe, clientes, servicos, produtos, salvarOS, salvarCliente, usuarioAtual \}\)/, 'function Agenda({ ordens, nomeCliente, abrirOS, agendarOS, desagendarOS, empresa, equipe, clientes, servicos, produtos, salvarOS, salvarCliente, usuarioAtual, pedirConfirmacao })', 'agenda props');
once(/(<div className="flex items-center gap-4 mt-2 text-\[12px\] flex-wrap"><Endereco valor=\{os\.local\} local=\{os\.localServico\} compacto className="max-w-full" \/>\{empresa\.temEquipe&&<span[^\n]+<\/span>\}<\/div>)/, '$1\n              {os.data && os.status !== "concluida" && <button onClick={(e) => { e.stopPropagation(); pedirConfirmacao({ titulo:"Remover da agenda?", texto:`${os.numero} continuará existindo como OS, mas ficará sem data e horário.`, confirmar:"Remover agendamento", perigo:true, acao:()=>desagendarOS(os.id) }); }} className="mt-2 text-[12px] font-medium text-rose-600 hover:underline">Remover da agenda</button>}', 'agenda unschedule');

const finalHash = hash(s);
if (finalHash !== POST) throw new Error(`Round 3.1 output hash mismatch: expected ${POST}, got ${finalHash}`);
writeFileSync(file, s, 'utf8');
console.log(`Applied Round 3.1 readable codemod (${finalHash})`);
